language: c
script: "make && make test"
compiler: gcc

script:
  - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
  - gcc --version

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5

before_install:
  - sudo ./scripts/install_bats.sh

git:
  quiet: true
  depth: false
