language: c
sudo: required
script: 
  - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
  - gcc --version
  - make && make test
env:
  CC=gcc-5

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5

before_install:
  - sudo ./scripts/install_bats.sh

git:
  quiet: true
  depth: false
